// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent to categorize service requests.
 *
 * - categorizeServiceRequest - A function that categorizes a service request based on its description.
 * - CategorizeServiceRequestInput - The input type for the categorizeServiceRequest function.
 * - CategorizeServiceRequestOutput - The return type for the categorizeServiceRequest function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeServiceRequestInputSchema = z.object({
  description: z.string().describe('The description of the service request.'),
});

export type CategorizeServiceRequestInput = z.infer<typeof CategorizeServiceRequestInputSchema>;

const CategorizeServiceRequestOutputSchema = z.object({
  category: z.string().describe('The suggested category for the service request.'),
});

export type CategorizeServiceRequestOutput = z.infer<typeof CategorizeServiceRequestOutputSchema>;

export async function categorizeServiceRequest(input: CategorizeServiceRequestInput): Promise<CategorizeServiceRequestOutput> {
  return categorizeServiceRequestFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeServiceRequestPrompt',
  input: {schema: CategorizeServiceRequestInputSchema},
  output: {schema: CategorizeServiceRequestOutputSchema},
  prompt: `You are an AI assistant helping to categorize service requests for a city.

  Based on the description provided, suggest the most appropriate category for the request.

  Description: {{{description}}}
  `,
});

const categorizeServiceRequestFlow = ai.defineFlow(
  {
    name: 'categorizeServiceRequestFlow',
    inputSchema: CategorizeServiceRequestInputSchema,
    outputSchema: CategorizeServiceRequestOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
